name: Test Project
on: push
jobs:
  test:
  runs-on: ubuntu-latest
  steps:
  # this executing environment does not have your code automatically,
  # you need to check out your code first
    - name: Get code
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
      # some actions have configuration options and you can pass them under the 'with' key
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci # makes sure  that we're always using the exact same versions we used during development.
    - name: Run tests
      run: npm test