name: Section 4 workflow
on:
  pull_request:
    types: [opened, edited]
    branches: # the branches that will be targetted 
      - main # main, PR to the main branch
      - 'dev-*' # dev-new
      - 'feat/**' # feat/new/button
  workflow_dispatch:
  push:
    branches:
      - main # only main branch
      - 'dev-*' # Match any branch that starts with 'dev-'m does not allow more slashes, eg: 'dev-new-feature'
      - 'feat/**' # Allows other slashes in the branch namem eg: 'feat/new/menuitem'
    paths-ignore:
      - '.github/workflows/*' # Do not start a workflow when a file is changed in the .github/workflows folder
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying project..."