name: Deploy Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # this executing environment does not have your code automatically,
    # you need to check out your code first
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        # some actions have configuration options and you can pass them under the 'with' key
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        # run: npm ci # makes sure  that we're always using the exact same versions we used during development.
      - name: Run tests
        run: npm test
  deploy:
    needs: test # this job will run only if the 'test' job is successful
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying project..."
      

